#!/bin/bash


red='\033[1;31m'
green='\033[1;32m'
cyan='\033[1;36m'
NC='\033[0m' # No Color

case "$1" in
	angular)
		shopt -s dotglob
		sudo cp -an /Users/ryanschie/_Web/http/_libs/angular/angular-boilerplate/* `pwd`
		shopt -u dotglob
		sudo rm -R ".git"
		echo -e "${green}Boiled Angular template${NC}"
		;;
	 
	api)
		sudo cp -an /Users/ryanschie/_Web/http/_libs/laravel/laravel-api `pwd`
		sudo mv laravel-api api
		sudo rm -R "./api/.git"
		sudo rm "./api/.gitignore"
		echo -e "${green}Boiled API template${NC}"
		;;

	php)
		shopt -s dotglob
		sudo cp -an /Users/ryanschie/_Web/http/_libs/general/php-boilerplate/* `pwd`
		shopt -u dotglob
		echo -e "${green}Boiled PHP template${NC}"
		;;
	 
	*)
		echo -e "\n\tCopies boilerplates from ${cyan}$HTTP/_libs${NC}"
		echo -e "\tUsage: { ${green}angular${NC} | ${green}api${NC} }\n"
		exit 1

esac
